### PR TITLE
Add QC processes to pipeline

### PR DESCRIPTION
**Pull request by marc-jones**
This replaces PR #8

### CODE REVIEW

**Comment by marc-jones** [comment]
I had to change the tests which checked the UMITools process logs, as because the logs are now saved explicitly they are not longer saved to `.command.log`. Extracting the sample ID is a little janky, but seems to work.

**Review by samirelanduk — COMMENTED** [review]
Looks great - unless these are the established names I guess we should be consistent with underscores for process names (ie either CLIPQC and MULTIQC or CLIP_QC and MULTI_QC).

My only concern is the channels sending things out of sync again. CLIPQC takes log files from different processes for example, but am I right in saying that currently it could get the BOWTIE log from one sample, the STAR log from another sample, etc.?

(The merge conflict with master right now is because I changed some things in demultiplex.nf etc yesterday - I can fix those.)

**Comment by marc-jones** [comment]
Fair comment with the underscores, I guess as it's MULTIQC in the `nf-core/modules` repo, I'll change it to CLIPQC.

Regarding the channels sending stuff out of sync, I _think_ it's okay, as all inputs to CLIPQC are `.collect()`-ed, so CLIPQC should only run once for all samples. @amchakra's QC script extracts the experiment names and performs the joins itself. I'll confirm if this is the case though.

**Comment by marc-jones** [comment]
Just checked, and I was right, if multiple samples are passed to PRIMARY_CLIP_ANALYSIS then only one CLIPQC process is run. I did this by changing `Non-Coding RNA Analysis` to `Primary CLIP Analysis` for sample `iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5` in the test annotation file.

`tail` of the Nextflow process output:
```
[4c/515781] process > PRIMARY_CLIP_ANALYSIS:ICOUNT_SUMMARY (iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5)               [100%] 2 of 2 ✔
[33/eab3c6] process > PRIMARY_CLIP_ANALYSIS:ICOUNT_RNAMAPS (iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5)               [100%] 2 of 2 ✔
[37/70f592] process > PRIMARY_CLIP_ANALYSIS:ICOUNT_SIGXLS (iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5)                [100%] 2 of 2 ✔
[3d/d38574] process > PRIMARY_CLIP_ANALYSIS:ICOUNT_PEAKS (iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5)                 [100%] 2 of 2 ✔
[36/b42924] process > PRIMARY_CLIP_ANALYSIS:PEKA (iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5)                         [100%] 2 of 2 ✔
[3d/5d9758] process > PRIMARY_CLIP_ANALYSIS:CLIP_QC (Performing QC)                                                 [100%] 1 of 1 ✔
[-        ] process > NCRNA_ANALYSIS:TRIMGALORE                                                                     -
[5e/7954af] process > MULTIQC                                                                                       [100%] 1 of 1 ✔
Completed at: 13-Jun-2022 10:47:18
Duration    : 2m 25s
CPU hours   : 0.1
Succeeded   : 64
```

Structure of the CLIPQC `work` directory: 
```
(base) C02D7N62ML7J:imaps-nf jonesm5$ tree work/3d/5d97587cb744781e335488013f7a14/
work/3d/5d97587cb744781e335488013f7a14/
├── clippy
│   ├── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4_rollmean10_stdev1_minGeneCount5_Peaks.bed.gz -> /Users/jonesm5/Documents/projects/imaps-nf/work/8f/24616210de88305fc4d3ebb4e3fafb/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4_rollmean10_stdev1_minGeneCount5_Peaks.bed.gz
│   └── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5_rollmean10_stdev1_minGeneCount5_Peaks.bed.gz -> /Users/jonesm5/Documents/projects/imaps-nf/work/91/510097ac71face4cbec112f644e30c/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5_rollmean10_stdev1_minGeneCount5_Peaks.bed.gz
├── dedup
│   ├── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.log -> /Users/jonesm5/Documents/projects/imaps-nf/work/68/dd27a36b222d26ddbe84354e2480ff/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.log
│   └── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.log -> /Users/jonesm5/Documents/projects/imaps-nf/work/1e/8130de04b89e75aeef82be385ad689/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.log
├── dedup_mean_umis.tsv
├── dedup_metrics.tsv
├── dedup_ratio.tsv
├── dedup_reads.tsv
├── icount
│   ├── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.peaks.bed.gz -> /Users/jonesm5/Documents/projects/imaps-nf/work/c4/fa50b9499d932cbb4b726af34e11a7/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.peaks.bed.gz
│   └── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.peaks.bed.gz -> /Users/jonesm5/Documents/projects/imaps-nf/work/3d/d385744c1762b95ea874dfbfd965d6/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.peaks.bed.gz
├── mapped
│   ├── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.Log.final.out -> /Users/jonesm5/Documents/projects/imaps-nf/work/a9/a1bf4652cb298894789b59cfb9baa2/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.Log.final.out
│   └── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.Log.final.out -> /Users/jonesm5/Documents/projects/imaps-nf/work/a4/7cb66799258664f433d832215bc1ec/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.Log.final.out
├── mapping.tsv
├── mapping_metrics.tsv
├── paraclu
│   ├── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.peaks.bed.gz -> /Users/jonesm5/Documents/projects/imaps-nf/work/c5/8bc139c7edfb54c924e9c0aa2448a5/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.peaks.bed.gz
│   └── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.peaks.bed.gz -> /Users/jonesm5/Documents/projects/imaps-nf/work/90/bca999d051f7a32038b7020ae79892/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.peaks.bed.gz
├── peaks_metrics.tsv
├── peaks_xlinksite_coverage.tsv
├── premap
│   ├── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.out -> /Users/jonesm5/Documents/projects/imaps-nf/work/12/6dbe8e800337e2894e9086fd808a3c/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.out
│   └── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.out -> /Users/jonesm5/Documents/projects/imaps-nf/work/15/fc83e47b4aed7b11958d97fdd25a0a/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.out
├── total_peaks.tsv
├── xlinks
│   ├── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.bed.gz -> /Users/jonesm5/Documents/projects/imaps-nf/work/39/0ffc365f59ca3b7e9e27b01d3a60f9/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4.bed.gz
│   └── iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.bed.gz -> /Users/jonesm5/Documents/projects/imaps-nf/work/25/fab81a7f8df1ae73fbef0c00d9aad3/iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5.bed.gz
├── xlinks_counts.tsv
├── xlinks_in_peaks.tsv
├── xlinks_metrics.tsv
├── xlinks_ratio.tsv
└── xlinksites_in_peaks.tsv

7 directories, 28 files
```

A couple of the output files from CLIPQC, showing that both samples are being considered:
```
(base) C02D7N62ML7J:imaps-nf jonesm5$ head work/3d/5d97587cb744781e335488013f7a14/xlinks_counts.tsv 
exp     total_xlinks    total_xlinksites
iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4        365.0   154
iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5        389.0   188
```

```
(base) C02D7N62ML7J:imaps-nf jonesm5$ head work/3d/5d97587cb744781e335488013f7a14/dedup_ratio.tsv 
exp     ratio
iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_4        1.38
iCLIP_SmB_Cal51_NSsiRNA_20130808_LUc21_5        1.2
```

**Comment by samirelanduk** [comment]
Ah ok, I didn't realise CLIPQC ran only once.

When running locally I get an error with MULTIQC:

```
Usage: multiqc [OPTIONS] <analysis directory>

Error: Invalid value for '-c' / '--config': Path 'multiqc_config.yaml' does not exist.

This is MultiQC v1.9

For more help, run 'multiqc --help' or visit http://multiqc.info
```

Though I see the tests run fine, so not sure what's different in my environment. The file it's missing I see is in `/conf` - how does the process access this?

**Comment by samirelanduk** [comment]
That will be it - they aren’t run from the base directory on iMaps. As it’s constant can it be embedded in the process itself somehow?

**Comment by marc-jones** [comment]
Hmm, this might not be desirable as then the MultiQC process couldn't be reused in other pipelines. I know it's a local module already, but the only change to it relative to the nf-core/modules file is the version.

This is kind of linked to this issue: https://github.com/nextflow-io/nextflow/issues/1798

A potential option would be to use the `$moduleDir` implicit variable and have a folder of MultiQC config files in the module folder, but it doesn't get mounted when using Docker so it's not feasible here.

I wonder if the cleanest option would be to have a folder for these additional assets, with subdirectories with the same name as the pipeline.

**Review by samirelanduk — APPROVED** [review]
All working locally now - thanks for the name changes too. Will merge now and make it runnable by itself in a later release. Thanks!

**Pull request merged**
