### PR TITLE
Added MultiQC process

### PR DESCRIPTION
**Pull request by marc-jones**
There are a couple of issues with this PR. I'm happy to resolve them before merging, or if they aren't a big deal, this can be merged and the issues tracked.

The first is the MultiQC config Nobby wrote seems to require MultiQC version 1.9. I think if I was doing this properly I should create a local module with this older version [rather than changing the module](https://github.com/goodwright/imaps-nf/compare/feat-qc?expand=1#diff-650f7ca3a8b649868e23ee828ce4dabdf220f5e519869745cb41be856528fe65R4) in the `modules/nf-core` directory. Or understand why the config is version dependent and fix it. I'm happy to do either.

Another issue, the CLIP_QC command can in theory calculate statistics for the deduplication carried out by UMItools, but the UMI_DEDUP module doesn't output the log file required. Again, this could be fixed by creating a local module which does save the log file, and then [uncommenting the deduplication statistics part of the CLIP_QC template](https://github.com/goodwright/imaps-nf/compare/feat-qc?expand=1#diff-971a69d154e56c8acbbfe77e136dab3be6effbf23354fa8401c106253e6f56dbR82).

Finally, I put Nobby's MultiQC custom config file in the `conf` directory, which then gets staged by creating a new channel [here](https://github.com/goodwright/imaps-nf/compare/feat-qc?expand=1#diff-26c121e1cafa6b9b9916c2ea79056c706ed49709453fdbe962b253631d391707R35). Is `conf` only meant for Nextflow config files? And if so, where would make sense to keep the MultiQC config? Will hard coding the config location prove an issue when this is run on the server?

### CODE REVIEW

**Comment by samirelanduk** [comment]
Thanks Marc. I gather the main issue with editing the modules directly is that as it is against NF-core's way of doign things, it means the pipeline can't be submitted to them. Is that right @CharlotteAnne? From iMaps's point of view it's not a big deal (though I guess could make debugging harder in future) - depends what the ultimate aim with the pipeline is, beyond iMaps. Charlotte's call I think.

**Comment by CharlotteAnne** [comment]
I think on:
-  MultiQC version 1.9: agreed we should update to config to conform to nf-core module version, but perhaps this can be left until we go through the process of nf-core-ising everything - should we create an issue with a reminder to do this so it isn't forgotten?
- UMI-tools - I suppose the best thing to do would be to make a pull request to the nf-core module itself? again happy for this to be left for now but again perhaps should be recorded in an issue?  maybe we could make an nf-core project and tag all issues related to nf-core-isation in this?
- the conf directory stuff i think is @samirelanduk's jurisdiction?

**Comment by marc-jones** [comment]
That all makes sense. I'll have a bit of a go today trying to get the custom config to work with the newer MultiQC version, but if I don't manage it I'll move the v1.9 module to `local` so at least the `modules/nf-core` folder is clean. I'll also add the logging to UMI_DEDUP and create a PR over at `nf-core/modules`; as @CharlotteAnne says, better to add this upstream.

**Comment by marc-jones** [comment]
So, after some investigation, the issue with MultiQC versions [is a known bug](https://github.com/ewels/MultiQC/issues/1645) which will hopefully be fixed at some point. I've moved the old version of MultiQC to the `local` folder just to keep things clean.

Having a look at the `UMITOOLS_DEDUP` module, the latest version on `nf-core/modules` does output some `.tsv` files of statistics, although doesn't output the log file with Nobby's QC script parses. However, we might be able to get the same information from the `.tsv` files which are outputted using the built in UMITOOLS module of MultiQC. When I get back from Easter I can have a look if you like?

**Pull request closed without merging**
